from lib.pywordle import *
wordle = WordleSolver()
#print(wordle.remainingWords())
#wordle.reset()
#wordle.setTarget("moist")
#print(wordle.makeGuess("aloes"))
#print(wordle.makeGuess("asess"))
#wordle.sampleWords(1)
#print(list(wordle.testWord("aloes")))
wordle.setTarget("aback")
wordle.makeGuess("trmns")
print(wordle.makeGuess("mamma"))
wordle.sampleWords(5)
wordle.reset()
wordle.setTarget("aback")
assert(wordle.makeGuess("fuzzy") == 1352)
wordle.reset()
wordle.setTarget("acute")
assert(wordle.makeGuess("vivid") == 1328)